name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Create .nojekyll to bypass Jekyll processing
      - name: Disable Jekyll
        run: touch build/web/.nojekyll

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      
      # Enable Flutter web
      - name: Enable Flutter web
        run: flutter config --enable-web
      
      # Get dependencies
      - name: Get dependencies
        run: flutter pub get
      
      # Build web app with CanvasKit
      - name: Build web app
        run: flutter build web --web-renderer canvaskit --release --base-href "/${{ github.repository }}/"


      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web